name: check-all
version: 0.0.0

synopsis: TODO
description: TODO
license: GPL-3.0-only
author: Aaron VonderHaar
maintainer: gruen0aermel@gmail.com

build-type: Simple

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - DataKinds
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - PolyKinds
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

ghc-options:
  - -threaded
  - -O2
  - -Wall
  - -Wcompat
  - -Wredundant-constraints
  - -Werror=inaccessible-code
  - -Werror=incomplete-patterns
  - -Werror=missing-fields
  - -Werror=missing-home-modules
  - -Werror=overflowed-literals
  - -Werror=overlapping-patterns

dependencies:
  - base
  - directory
  - text
  - typed-process


executables:
  check-all:
    main: Main.hs
    source-dirs:
      - src
      - main


tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec >= 2.7.10
      - temporary
    build-tools: hspec-discover
