name: "Snapshot release"
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v17
      - run: nix-build
