name: "Snapshot release"
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    name: snapshot-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: '9.2.4'
      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: cabal-v1-${{ runner.os }}-${{ hashFiles('check-all.cabal') }}
      - run: cabal update
      - run: cabal test
      - run: cabal install --installdir=./dist
      - uses: actions/upload-artifact@v2
        with:
          name: check-all-${{ github.sha }}-${{ runner.os }}
          path: dist/
